---
language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - docker build --tag python-docker .
  - docker run -d -p 8000:5000 python-docker
  - ls

install:
  - pip install behave
  - pip install requests

script:
  - behave

after_script:
  - docker kill $(docker ps -q)