---
language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - docker build --tag python-docker .
  - docker run -d -p 8000:5000 python-docker
  - ls

install:
  - pip install behave
  - pip install requests
  - pip install coveralls

script:
  - curl localhost:8000
  - behave
  - coverage run --source='.' -m behave

after_script:
  - coveralls
  - docker kill $(docker ps -q)